tpch:
  target: prod
  outputs:
    prod:
      type: snowflake
      threads: 1
      account: id11111.eu-west-1
      user: USER_NAME
      password: password
      role: USER_NAME
      database: USER_NAME_DB
      schema: MARTS
      warehouse: YOUR_WAREHOUSE
      query_tag: dbt
      client_session_keep_alive: True
